[2024-04-12T09:02:25.177+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 20043131.20043131 manual__2024-04-12T09:02:14.690798+00:00 [queued]>
[2024-04-12T09:02:25.201+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 20043131.20043131 manual__2024-04-12T09:02:14.690798+00:00 [queued]>
[2024-04-12T09:02:25.203+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-12T09:02:25.271+0000] {taskinstance.py:2214} INFO - Executing <Task(BashOperator): 20043131> on 2024-04-12 09:02:14.690798+00:00
[2024-04-12T09:02:25.311+0000] {standard_task_runner.py:60} INFO - Started process 84 to run task
[2024-04-12T09:02:25.329+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '20043131', '20043131', 'manual__2024-04-12T09:02:14.690798+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpkn5vh5op']
[2024-04-12T09:02:25.355+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask 20043131
[2024-04-12T09:02:36.904+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 3 for task 20043131 ((psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8); 84)
[2024-04-12T09:02:41.383+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-12T09:02:41.459+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
